sudo: required
dist: focal
language: python
python:
  - "3.7"
env:
  global:
    - ROLE_NAME: exabgp
    - secure: Q1UiUgD91Nod32LGOKKEQN+Uz+eFxQmfmb1uzpHvcKKYS8jqTQrggWzd/Et2i4M2xPctYwPC5EDjLKiyLh77YMx00b4RHU+ltlfxO7QrpnoAr3SxN7TPsWOktSIqf8fU2JHtqSrDYZBORdgpG1IO0rrPcDUMQ8lwvsc9oFOqNhT4I8fw93m4fcqaHMuhS90VblYik5LTztwLrvLLGOo0lYkoExfOSuiwrG5R+eR7a/ZF9OGoghyzDXSSfPKX0p54cGx2fWmbgUpFaufoasK6d7vLi8Km1H8YKKteP/ES0Kcj0bZI4zp9Yz9rK0LvhBFLt8gwIaNEt9FAA+r+4zrDBysrmGe0O+mZYt04x+S1Ic914szbuX/jY+YDl0SD7R+Okp4KgfVvomG09E+qxIURgdP2V1zpRrB6/3SJeYrfBY40oLKyysWfE2S+aNoLCz5hkr6lr4E2AN3AVVebdIX3rlb96VSR9TteOmx0kJuDZ9tmn/2h0mcIFf1S8dMJlTNJjpv+9I/w7FulgPcZEFlwORqUyU3tL2MP+nW0G6mvuGAIBg3pDEnDcCUK61jxrRaenRusoeASoeAxEbr7eWSrGD/LriYxcAYhh7cNwjIYaO5T3hAVQFdAnY4nw/RXnF7lzpHkDjGeQV+lk9So4Ku2eoRFqi6C0P6ErPRwu/FIRwk=
    - secure: INH+Pmh7E65tpnYP4RvfKgxvKSqH2xc9kEVrJjZkm/jZo40nDEE+V7z1NvkYVDptrKbjWoHghkZgxBGkSirXz7dPgTo/slMdJ+w+Vyy1GI+ZOQjKMQT3i5ScbUacpG7Via1a2ZM7h0wymAxLOQncyLZ5qcTDUSx3bLz373Ye9STAFqWn45ANlP9S0GGLiGXcVvCp2tDT6TOiScK0bNecHMVCBcDRj9dzxqxrrDzwJ2qhghtjF1e/Vh87WH9+FhS/CoRjFZCByEhN7eGuRWGy7G1NFN5DDC462/TT08Fk1tb60z1PGkAfNw4rbwPCd5ORaSRzyu7a5tMcudtyZdWgnHEcf0bWW5tSnM10/dcSoy8EkD18v3Zh8WQb9LzPN66TfTCFZ1Gi80kpwNHGFuspp3C3b9IYrMmG3YCjjNMOsyGBgg5YfzxbpuSSXnjOxvPED5g5WWhUjATR0nZ/oM8YEee5li1C/EIiwOQRBPQd/Uq4UC/wMQpS/Ib2BSdyOiiid4BUiiJbkeNXR9KfCXcocUADbpSaMspsCUhDzu+bH0jvOV2ApJofR9qy9/x7iwrLlnJ9oSv03JuYnSeHMw62cdm/YV3+SctI3/qx7OsgCVnPigXofsqOd9bHSsQw54d7lcxCoBN07kcU7bI2glmZpBXIEq0g+6a5SruZm+Jpdi8=
  jobs:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
services: docker
install:
  - pip install molecule-docker yamllint ansible-lint
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#  - cd ../
#  - GALAXY_ROLE_NAME=$(echo "${ROLE_NAME}" | tr '-' '_')
#  - mv ansible-role-$ROLE_NAME hybridadmin.$GALAXY_ROLE_NAME
#  - cd hybridadmin.$GALAXY_ROLE_NAME
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
