---
- name: Load in project specific vars
  include_vars: "../vars/main.yml"

- name: Add dir to system-wide $PATH.
  copy:
    dest: /etc/profile.d/custom-path.sh
    content: 'PATH=$PATH:{{ user_bin_dir }}'

- name: exabgp set required vars
  ansible.builtin.set_fact:
    required_dirs: "{{ exabgp_dirs }}"
    required_tpls: "{{ exabgp_templates }}"

- name: Redhat | Enable EPEL rpm repo
  action: >
    {{ ansible_pkg_mgr }} name=epel-release state=present update_cache=yes
  become: yes
  when: (ansible_os_family == 'RedHat' and ansible_distribution_major_version == "7")

- name: Python3 Install
  include_tasks:
    file: python.yml

- name: App install
  include_tasks:
    file: install.yml
