---
- name: Converge
  hosts: all
  remote_user: root
  any_errors_fatal: true

  vars:
    bgp_neighbors:
      - {ip: 192.168.50.10, desc: "r2"}
    local_as: 65340
    remote_as: 65359
    community_list: "65359:500 65359:5000"
    anycast_procs:
      - name: dns1v4
        cidr: 192.168.59.188/32
      - name: dns2v4
        cidr: 192.168.59.189/32
    test_cmd: "dig +notcp +timeout=1 +tries=1 +short @127.0.0.1 a.root-servers.net"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: ansible-role-exabgp
