---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: ansible-role-${ROLE_NAME:-exabgp}-${MOLECULE_DISTRO:-centos7}
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  options:
    v: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      timeout: 60
      stdout_callback: yaml
      bin_ansible_callbacks: yes
      verbosity: 1
verifier:
  name: ansible
  enabled: False
