name: run_molecule

on: [push]

jobs:
  run_linting:
    uses: hybridadmin/reuse-workflows/.github/workflows/linting.yml@main
    secrets: inherit
#    with:
#      working_directory: 'hybridadmin.exabgp'

  run_molecule_test:
    needs:
      - run_linting
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        distro:
          - image: centos
            tag: 8
          - image: ubuntu
            tag: noble
          - image: ubuntu
            tag: jammy
          - image: debian
            tag: 12
    uses: hybridadmin/reuse-workflows/.github/workflows/molecule.yml@main
    secrets: inherit
    with:
      distro_image: '${{ matrix.distro.image }}'
      distro_tag: '${{ matrix.distro.tag }}'
      working_directory: 'hybridadmin.exabgp'

##
