name: run_molecule

on: [push]

jobs:
  run_molecule_test:
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        distro:
          - image: centos
            tag: 8
          - image: ubuntu
            tag: noble
          - image: ubuntu
            tag: jammy
          - image: debian
            tag: 12
    uses: hybridadmin/reuse-workflows/.github/workflows/molecule.yml@main
    secrets: inherit
    with:
      distro_image: '${{ matrix.distro.image }}'
      distro_tags: '${{ matrix.distro.tags }}'
      working_directory: 'hybridadmin.exabgp'
